import 'package:picpay_clone/src/models/transction_model.dart';

final List<TransctionModel> transactions = <TransctionModel>[
  TransctionModel(
    urlAvatar:
        'https://noticiasdemogi.com.br/wp-content/uploads/2021/06/cartao-credito-picpay.png',
    value: 189.90,
    description: 'esteve em',
    fromUser: 'Você',
    toUser: 'Cento Automotivo',
    days: 2,
    period: 'dias',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
    urlAvatar: 'https://logospng.org/download/pix/logo-pix-icone-1024.png',
    value: 69.90,
    description: 'enviou um',
    fromUser: 'Você',
    toUser: 'PIX',
    days: 4,
    period: 'dias',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
    urlAvatar:
        'https://noticiasdemogi.com.br/wp-content/uploads/2021/06/cartao-credito-picpay.png',
    value: 10.50,
    description: 'esteve em',
    fromUser: 'Você',
    toUser: 'Pg *cantina Zé',
    days: 5,
    period: 'dias',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
    urlAvatar:
        'https://noticiasdemogi.com.br/wp-content/uploads/2021/06/cartao-credito-picpay.png',
    value: 350.00,
    description: 'esteve em',
    fromUser: 'Você',
    toUser: 'Vet Animal Feliz',
    days: 1,
    period: 'semana',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
      urlAvatar: 'https://logospng.org/download/pix/logo-pix-icone-1024.png',
      value: 300.00,
      description: 'recebeu um',
      fromUser: 'Você',
      toUser: 'Pix',
      days: 1,
      period: 'semana',
      likes: 0,
      comments: 0,
      isdeposit: true),
  TransctionModel(
    urlAvatar: 'https://logospng.org/download/pix/logo-pix-icone-1024.png',
    value: 58.90,
    description: 'enviou um',
    fromUser: 'Você',
    toUser: 'Pix',
    days: 2,
    period: 'semana',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
    urlAvatar:
        'https://noticiasdemogi.com.br/wp-content/uploads/2021/06/cartao-credito-picpay.png',
    value: 905.90,
    description: 'esteve em',
    fromUser: 'Você',
    toUser: 'Mercadinho green',
    days: 2,
    period: 'semana',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
    urlAvatar:
        'https://pixel.cuboup.com/wp-content/uploads/edd/2021/08/Icone-Codigo-de-Barras-1.jpg',
    value: 189.90,
    description: 'pagou um',
    fromUser: 'Você',
    toUser: 'Boleto',
    days: 2,
    period: 'dias',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
    urlAvatar:
        'https://noticiasdemogi.com.br/wp-content/uploads/2021/06/cartao-credito-picpay.png',
    value: 19000.90,
    description: 'esteve em',
    fromUser: 'Você',
    toUser: 'Honda',
    days: 1,
    period: 'mês',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
    urlAvatar: 'https://logospng.org/download/pix/logo-pix-icone-1024.png',
    value: 7.000,
    description: 'recebeu um',
    fromUser: 'Você',
    toUser: 'Pix',
    days: 2,
    period: 'mês',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
    urlAvatar:
        'https://noticiasdemogi.com.br/wp-content/uploads/2021/06/cartao-credito-picpay.png',
    value: 240.90,
    description: 'esteve em',
    fromUser: 'Você',
    toUser: 'Cento Automotivo Shell',
    days: 2,
    period: 'meses',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
    urlAvatar: 'https://logospng.org/download/pix/logo-pix-icone-1024.png',
    value: 4000.90,
    description: 'enviou um',
    fromUser: 'Você',
    toUser: 'Pix',
    days: 3,
    period: 'meses',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
    urlAvatar:
        'https://noticiasdemogi.com.br/wp-content/uploads/2021/06/cartao-credito-picpay.png',
    value: 4999.90,
    description: 'esteve em',
    fromUser: 'Você',
    toUser: 'CVC Passagens',
    days: 4,
    period: 'meses',
    likes: 0,
    comments: 0,
  ),
  TransctionModel(
      urlAvatar: 'https://logospng.org/download/pix/logo-pix-icone-1024.png',
      value: 4000.90,
      description: 'recebeu um',
      fromUser: 'Você',
      toUser: 'Pix',
      days: 4,
      period: 'meses',
      likes: 0,
      comments: 0,
      isdeposit: true),
];
